### ISSUE TITLE
A lot of DNS traffic from bridge.

### ISSUE THREAD

**Issue by SDeath667** [virtualzone/landroid-bridge#98]
After updating to the last commit from yesterday everything started working again and I get the information I want. 
But I am still seeing a lot of DNS traffic coming from the bridge. After about 12 hours of running now I am at 80.000 requests, this is 4x more than my 2nd device in the list with 20.000 which is my Fibaro Home Center 2 that is controlling my entire house and fetching lots of data from the internet to base my scenes on.

Why is the bridge generating so much traffic, all the traffic goes to a Amazon AWS server.
![Landroid Bridge 1](https://user-images.githubusercontent.com/26328909/79438095-5f2f8c00-7fd3-11ea-954f-4e5691b0b45d.jpg)
![Landroid Bridge 2](https://user-images.githubusercontent.com/26328909/79438097-5fc82280-7fd3-11ea-8d33-0ae9ec340164.jpg)
![Landroid Bridge 3](https://user-images.githubusercontent.com/26328909/79438171-7c645a80-7fd3-11ea-965d-66e527840a41.jpg)

**Comment by KoKia13** [comment]
Same, then AWS blacklist the client IP :/

**Comment by SDeath667** [comment]
142.000 requests in 24 hours.

**Comment by SDeath667** [comment]
It is now back to normal after I guess exactly 24 hours.
@KoKia13 have you seen the same behaviour?

**Comment by KoKia13** [comment]
When I was using the bridge and was probably blacklisted regularly. I've made some tcpdump/wireshark checks and seen lot of requests.  I've tried with a cron task to stop the service during the night... Few weeks ago with the version with the new auth, same. 
I've completely stopped to use the bridge now. And directly with Home Assistant making a rest request every minutes and parsing the json values from the Worx api website.
I'm not able to push actions via AWS, (curl commands) I'm still blacklisted, I think. But it's not my main need. 
I'm triggering notifications when the mower is trapped, at home, etc.

Worx support:
> Good Morning,
> we've noticed on our backend that you're using an unofficial client to connect to the IoT. Unfortunately this is not possible at the moment, because these clients poll the Landroid way too many times per day and they generate a lot of traffic on the server side.
> For this reason, when the server detects such unusual amounts of messages, they shut down the client for 24 hours. We advise you to use the official app to connect to the IoT.
> Thank you for your understanding.
> Kind Regards
> Azzurra

**Comment by ciechompl** [comment]
@KoKia13 would you be so kind and share your config how do you make those rest requests directly to worx api ? 
To be honest I do not need a full functionality of the landroid-bridge (even if idea itself is very cool :) ) but simple status info what my mower is doing at the moment is completely enough for me and most probably for many users here :)

**Comment by KoKia13** [comment]
I'm retrieving a token, but this token cannot be passed automatically to the authentication of the rest command, so I'm storing it manually in the secret file.
Based on this topic : https://easydomoticz.com/forum/viewtopic.php?t=8246
I'm using his client_secret and it's works,Next,  I'll try to find one of my android installed app.
HA Sensors:
```
  - platform: rest
    name: worx_token
    json_attributes:
      - access_token
    resource: https://api.worxlandroid.com/api/v2/oauth/token
    method: POST
    headers:
      Content-Type: application/json
    payload: '{"client_id": 1, "grant_type": "password", "scope": "*", "client_secret": "nCH3A0WvMYn66vGorjSrnGZ2YtjQWDiCvjg7jNxK", "username": "<YOUR WORX EMAIL>", "password":"<YOUR WORX PASSWORD>"}'
    scan_interval: 604800 # 7j
    value_template: '{{ value_json.value }}'

  - platform: rest
    name: worx_sensors
    json_attributes:
      - cfg
      - dat
    resource: https://api.worxlandroid.com/api/v2/product-items/<YOUR LANDROID SERIAL NUMBER>/status
    method: GET
    headers:
      Content-Type: application/json
      Authorization: !secret worxtoken
      #Authorization: 'Bearer {{ states.sensor.worx_token.attributes.access_token }}'
    scan_interval: 70
    value_template: '{{ value_json.value }}'

```
HA secret:
`worxtoken: "Bearer <YOUR WORX TOKEN>"`
